/* tslint:disable */
/* eslint-disable */
/**
 * ShellHub Enterprise
 * ShellHub Enterprise.  It documents all routes provided by ShellHub Enterprise.   NOTICE: THE API IS NOT STABLE YET; ERROR AND INCONSISTENCIES MAY OCCUR. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contato@ossystems.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

